### ISSUE TITLE
Will you release the codes for training?

### ISSUE THREAD

**Issue by cxzhou95** [Elody-07/AWR-Adaptive-Weighting-Regression#1]

**Comment by Elody-07** [comment]
Main components of our method has already been presented. And training follows standard pipeline. We are working on an improved version of AWR and will release full codes upon progress. Lately we will release pre-trained model on NYU dataset.

**Comment by cxzhou95** [comment]
> Main components of our method has already been presented. And training follows standard pipeline. We are working on an improved version of AWR and will release full codes upon progress. Lately we will release pre-trained model on NYU dataset.

Thank you for your reply.
