### ISSUE TITLE
Where is the inferencing code?

### ISSUE THREAD

**Issue by NahianAlindo** [Elody-07/AWR-Adaptive-Weighting-Regression#10]
Your work seems to be really good, and the claims you make on different datasets seems to be really suitable for my project. Which file contains the inferencing code? I can't seem to understand which one it is.  I ask this for testing out on some videos to see how the model would perform within a real-time setting on videos.

I want to test your work out with the pretrained model files of MSRA, HANDS 2017. Have you guys been able to retrieve them from your university computer yet?

Please help me out here by guiding me to find and use the inferencing code.

**Comment by Elody-07** [comment]
Sorry for the delay. Inference code is in `test.py` and currently we only provide pretrained model on NYU dataset.
