### ISSUE TITLE
Application Using A Datastream

### ISSUE THREAD

**Issue by thehiddenwaffle** [Elody-07/AWR-Adaptive-Weighting-Regression#14]
I am an undergrad trying to utilize this algorithm for augmented reality using a video stream from a Kinect V2 so obviously most of the work I'm doing is copy pasting pieces from nyu_loader.py and converting the dataset to work with a video stream, I've read through the paper and the code surrounding the model, and I believe that I'm mostly good but there are some places that I'm unsure what to do and would appreciate guidance:

1. I haven't figured out what the alternative coordinate system(uvd) is yet(if there's any references you could guide me to I'd love to read them), and because of that I don't quite understand the first 2 magic number of paras = (588.03, 587.07, 320., 240.) in nyu_loader, obviously the second 2(320., 240.) numbers map to the resolution of the Kinect V1, but I'm unsure what the first 2 are and if I need to change them to work with a Kinect V2 frame?

2. Is there a place I can find a diagram of the hand joint names and their corresponding positions on the hand? I looked at the NYU hand site but couldn't find them.

3. When finding hands in a video stream, I won't be given the hand center, do you have any recommendations for finding the center? The paper mentions using a network for finding centers but it doesn't mention which one. 

4. Are there any major problems you can plainly forsee that I'm not seeing yet? Things related to the differences between the Kinect V1 and V2 perhaps?

My background is mostly in using opencv for small projects and this is my first time using a CNN for image processing

**Comment by Elody-07** [comment]
Hi, 
Thanks for your interest.
1. The uvd we used in our method is coordinate system. The paras corresponds to the intrinsic param of depth camera.
2. This is a dataset-related question, you can check the config file in dataset.
3. You can simply threshold points that are nearest to the camera. This requires no other objects between your hand and the camera.
