### ISSUE TITLE
dataloader issue from numpy to torch.tensor

### ISSUE THREAD

**Issue by re20100801** [Elody-07/AWR-Adaptive-Weighting-Regression#4]
Dear Auther:
        In released code, method "__getitem__" return numpy format data as below:
             return img[np.newaxis, :].astype(np.float32), jt_xyz.astype(np.float32), jt_uvd.astype(np.float32), center_xyz.astype(np.float32), M.astype(np.float32), cube.astype(np.float32)
        But in "test.py", code directly use them as torch tensor as below(Line 59):
             input = img.cuda()
             jt_uvd_gt = jt_uvd_gt.detach().cpu().numpy()
             jt_uvd_pred = jt_uvd_pred.detach().cpu().numpy()
             jt_xyz_gt = jt_xyz_gt.detach().cpu().numpy()
             center_xyz = center_xyz.detach().cpu().numpy()
             M = M.detach().numpy()
             cube = cube.detach().numpy()
       Is that allowed? During my implementation, this part report bug.
       Thanks in advance.

LOG as below:
  File "train.py", line 116, in train
    input = img.cuda()
AttributeError: 'numpy.ndarray' object has no attribute 'cuda'

**Comment by Elody-07** [comment]
In our code, we use torch.utils.data.Dataloader to load dataset. It will convert numpy array to torch Tensor. If you are loading data by yourself, you should convert it to torch Tensor first.

**Comment by re20100801** [comment]
Thanks， I got your point~
