### ISSUE TITLE
About Center Point File

### ISSUE THREAD

**Issue by re20100801** [Elody-07/AWR-Adaptive-Weighting-Regression#8]
Dear Author:
       In your AAAI 2020 paper, you said "we first train a small separated 2D CNN to attain hand center and extract hand regions from depth images". 
       During our test, there are some error in the HAND CENTER file provided by V2V-PoseNet
       Did you use the same HAND CENTER as V2V-PoseNet provided or you make a new one?
Thanks in advance!

**Comment by Elody-07** [comment]
We made a new one.

**Comment by re20100801** [comment]
Do you have a test about this part? 
I mean how much error can be reduced by replace the Center Point file?
Any approximate estimation would be nice too~

**Comment by re20100801** [comment]
Dear Author:
      Could you release your center point file as V2V which are used in A2J and JGR-P2O?
      It will be very helpful for fairly comparison with other work.
Thank you in advance!
Best

comparison
--


with

**Comment by Elody-07** [comment]
Sorry about the delay. I didn't make it clear before. For HANDS19 dataset, we trained centers by ourselves. For other datasets, we use centers provided by V2V for fair comparison.
